- hosts: all
  become: true
  vars:
    avax_network_id: "{{ lookup('env', 'AVAX_NETWORK_ID') }}"
    avax_http_host: "{{ lookup('env', 'AVAX_HTTP_HOST') }}"
    avax_http_port: "{{ lookup('env', 'AVAX_HTTP_PORT') }}"
    avax_log_level: "{{ lookup('env', 'AVAX_LOG_LEVEL') }}"
    public_ip: "{{ lookup('env', 'REMOTE_PUBLIC_IP') }}"
    avax_http_tls_enabled: "{{ lookup('env', 'AVAX_HTTP_TLS_ENABLED') }}"
    avax_staking_enabled: "{{ lookup('env', 'AVAX_STAKING_ENABLED') }}"
    avax_staking_port: "{{ lookup('env', 'AVAX_STAKING_PORT') }}"
    avax_bootstrap_ips: "{{ lookup('env', 'AVAX_BOOTSTRAP_IPS') }}"
    avax_bootstrap_ids: "{{ lookup('env', 'AVAX_BOOTSTRAP_IDS') }}"
    avax_executable_name: avalanchego
    avax_plugin_location: /usr/bin
    avax_user: avax
    avax_db_dir: "/var/avax-storage/avax/data/shared_{{ avax_network_id }}_0"
    avax_staking_cert_location: "{{ avax_db_dir }}/cert_keys"
    avax_staking_key_location: "{{ avax_db_dir }}/cert_keys"
    avax_release_url: "{{ lookup('env', 'AVAX_RELEASE_URL') }}"
    avax_release_folder: /tmp/avax
  tasks:
    - name: Create avax user
      tags:
        - setup
        - users
      user:
        name: "{{ avax_user }}"
        state: present
        append: true
        create_home: true
        shell: /bin/bash

    - name: Upload avax executable
      tags:
        - never
        - upload_exec
      copy:
        src: "../../build/{{item}}"
        dest: /usr/bin
      with_items:
        ['avalanchego', 'plugins/evm']

    - name: Remove old release folder
      tags:
        - download_release
      file:
        state: absent
        path: "{{ avax_release_folder }}"

    - name: Re-create release folder
      tags:
        - download_release
      file:
        path: "{{ avax_release_folder }}"
        mode: "0750"
        state: directory
        owner: "{{ avax_user }}"
        group: "{{ avax_user }}"

    - name: Upload run file
      tags:
        - setup
        - upload_exec
      template:
        src: avax_run
        dest: /usr/bin/

    - name: Fix avalanchego executable permissions
      tags:
        - chmod
        - upload_exec
        - download_release
      file:
        dest: "/usr/bin/{{ avax_executable_name }}"
        mode: g+rx,o+rx

    - name: Fix evm plugin executable permissions
      tags:
        - chmod
        - upload_exec
        - download_release
      file:
        dest: "/usr/bin/evm"
        mode: g+rx,o+rx

    - name: Fix run file permissions
      tags:
        - setup
        - chmod
        - upload_exec
      file:
        dest: /usr/bin/avax_run
        mode: g+rx,o+rx

    - name: Create avax data folder
      tags:
        - setup
        - folders
        - upload_keys
      file:
        path: "{{ avax_db_dir }}"
        mode: "0750"
        state: directory
        owner: "{{ avax_user }}"
        group: "{{ avax_user }}"

    - name: Install avax unit files
      tags:
        - setup
        - systemd
      copy:
        src: "avalanchego.service"
        dest: "/etc/systemd/system/avax.service"

    - name: Upload validator certification files
      tags:
        - never
        - upload_keys
      copy: 
        src: "../../assets/cert_keys"
        dest: "{{ avax_db_dir }}"
        owner: "{{ avax_user }}"
        group: "{{ avax_user }}"

    - name: Setup logrotate
      tags:
        - setup
        - logrotate
      template:
        mode: u=rw,g=r,o=r
        src: logrotate.conf
        dest: "/etc/logrotate.d/avax"

    - name: Add cronjob for logrotate
      tags:
        - setup
        - logrotate
        - cron
      cron:
        name: "logrotate avax"
        minute: "0"
        hour: "*"
        job: "/usr/sbin/logrotate /etc/logrotate.d/avax --state {{ avax_db_dir }}/log/logrotate-state"
        user: "{{ avax_user }}"

    - name: Enable service avax
      tags:
        - systemd
        - run
        - restart
      systemd:
        name: avax
        state: restarted
        enabled: true
        daemon_reload: true
    
    - name: Delete Executables
      tags:
        - delete_exec
      shell: /bin/rm /usr/bin/avalanchego /usr/bin/evm

    - name: Delete Avalanchego database
      tags:
        - delete_db
      shell: sudo rm -rf /var/avax-storage/avax/data/shared_statalanche_0/statalanche/v1.0.0/*
